name: ReLBM
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - comm=0.2.2
  - debugpy=1.8.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.10.14
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pyzmq=26.0.3
  - readline=8.2
  - setuptools=70.0.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - pip:
      - absl-py==2.1.0
      - aiofiles==24.1.0
      - aiohttp==3.9.5
      - aioprocessing==2.0.1
      - aiosignal==1.3.1
      - ale-py==0.8.1
      - alembic==1.13.2
      - analytics-python==1.2.9
      - annotated-types==0.7.0
      - anyio==4.4.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - backoff==2.2.1
      - box2d-py==2.3.5
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - chex==0.1.87
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==0.29.37
      - decorator==4.4.2
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - emoji==2.12.1
      - etils==1.7.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - flax==0.10.1
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - google-pasta==0.2.0
      - gql==3.5.0
      - graphql-core==3.2.3
      - greenlet==3.0.3
      - grpcio==1.64.1
      - gymnasium==0.29.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.0
      - ipywidgets==8.1.3
      - janus==1.0.0
      - jax==0.4.29
      - jax-cfd==0.2.1
      - jax-cuda12-pjrt==0.4.29
      - jax-cuda12-plugin==0.4.29
      - jaxlib==0.4.29
      - jaxtyping==0.2.34
      - jinja2==3.1.3
      - jmp==0.0.4
      - jupyterlab-widgets==3.0.11
      - keras==3.4.1
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - llvmlite==0.43.0
      - lz4==4.3.3
      - mako==1.3.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mujoco==3.1.6
      - mujoco-py==2.1.2.14
      - multidict==6.0.5
      - namex==0.0.8
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvcc-cu12==12.5.40
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - openai==1.35.3
      - opencv-python==4.10.0.82
      - opt-einsum==3.3.0
      - optax==0.2.3
      - optree==0.12.1
      - optuna==3.6.1
      - orbax-checkpoint==0.5.15
      - pandas==2.2.2
      - pettingzoo==1.24.3
      - pillow==10.3.0
      - pooch==1.8.2
      - proglog==0.1.10
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pycparser==2.22
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygame==2.5.2
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - python-json-logger==2.0.7
      - pytorch-triton==3.0.0+45fff310c8
      - pytz==2024.1
      - pyvista==0.43.9
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rtree==1.2.0
      - scipy==1.13.1
      - scooby==0.10.0
      - seaborn==0.13.2
      - sentry-sdk==2.6.0
      - setproctitle==1.3.3
      - shimmy==1.3.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.31
      - stable-baselines3==2.3.2
      - swig==4.2.1
      - sympy==1.12
      - tenacity==8.4.2
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.61
      - termcolor==2.4.0
      - tianshou==0.5.1
      - tiktoken==0.7.0
      - toolz==1.0.0
      - torch==2.4.0.dev20240610+cu124
      - torchaudio==2.4.0.dev20240610+cu124
      - torchvision==0.19.0.dev20240610+cu124
      - tqdm==4.66.4
      - tree-math==0.2.1
      - trimesh==4.4.1
      - triton==2.3.1
      - typeguard==2.13.3
      - tzdata==2024.1
      - urllib3==2.2.1
      - vtk==9.3.0
      - wandb==0.17.2
      - weave==0.50.5
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - yarl==1.9.4
